// Catégories pour les formations non-scolaires (liste étendue)
export const categories = [
  'Langues étrangères',
  'Informatique et numérique',
  'Musique et arts',
  'Sports et bien-être',
  'Développement personnel',
  'Cuisine et gastronomie',
  'Photographie et vidéo',
  'Bricolage et DIY',
  'Entrepreneuriat',
  'Préparation aux concours',
  'Formation professionnelle',
  'Santé et paramédical',
  'Mode et design',
  'Environnement et écologie',
  'Sciences humaines',
  'Artisanat et métiers manuels',
  'Danse et expression corporelle',
  'Théâtre et arts dramatiques',
  'Écriture et littérature',
  'Méditation et spiritualité',
  'Relations et communication',
  'Finance et investissement',
  'Marketing digital',
  'Data science et IA',
  'Cybersécurité',
  'Droit et juridique',
  'Immobilier',
  'Agriculture urbaine',
  'Permaculture',
  'Premiers secours',
  'Sophrologie',
  'Yoga et disciplines associées',
  'Coaching professionnel',
  'Gestion de projet',
  'Leadership et management',
  'Langue des signes',
  'Calligraphie',
  'Poterie et céramique',
  'Menuiserie',
  'Mécanique automobile',
  'Aéronautique',
  'Astronomie',
  'Oenologie et dégustation',
  'Mixologie',
  'Pâtisserie',
  'Chocolaterie',
  'Comptabilité',
  'Ressources humaines',
  'Tourisme et hôtellerie',
  'Event management',
  'Drones et pilotage',
  'Jeux vidéo et e-sport',
  'Cryptomonnaies et blockchain',
  'Bijouterie et joaillerie',
  'Stylisme',
  'Reliure et restauration de livres',
  'Généalogie',
  'Paléontologie',
  'Survie en milieu naturel',
  'Plongée sous-marine',
  'Voile et navigation',
  'Autre',

];